export const shadeHistory = [
    {
        rollNo: "001",
        quantity: 118,
        lab: [21.3, 1.1, -6.8],
        deltaE: 0.64,
        shade: "A",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-HM-NV-01",
        date: "2026-03-01",
        supplier: "Arvind Mills",
        buyer: "H&M"
    },
    {
        rollNo: "002",
        quantity: 117,
        lab: [21.0, 1.2, -6.3],
        deltaE: 1.73,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-HM-NV-01",
        date: "2026-03-01",
        supplier: "Arvind Mills",
        buyer: "H&M"
    },
    {
        rollNo: "003",
        quantity: 114,
        lab: [18.4, 2.0, -4.8],
        deltaE: 4.31,
        shade: "D",
        decision: "HOLD",
        image: null,
        orderId: "LOT-HM-NV-01",
        date: "2026-03-01",
        supplier: "Arvind Mills",
        buyer: "H&M"
    },
    {
        rollNo: "004",
        quantity: 112,
        lab: [17.7, 2.5, -4.1],
        deltaE: 5.86,
        shade: "E",
        decision: "REJECT",
        image: null,
        orderId: "LOT-HM-NV-01",
        date: "2026-03-01",
        supplier: "Arvind Mills",
        buyer: "H&M"
    },
    {
        rollNo: "005",
        quantity: 128,
        lab: [91.8, -0.1, 2.1],
        deltaE: 0.36,
        shade: "A",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-PRL-WH-02",
        date: "2026-03-02",
        supplier: "Vardhman Textiles",
        buyer: "PRL (Polo Ralph Lauren)"
    },
    {
        rollNo: "006",
        quantity: 125,
        lab: [90.6, 0.6, 1.3],
        deltaE: 2.14,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-PRL-WH-02",
        date: "2026-03-02",
        supplier: "Vardhman Textiles",
        buyer: "PRL (Polo Ralph Lauren)"
    },
    {
        rollNo: "007",
        quantity: 124,
        lab: [89.9, 1.0, 0.9],
        deltaE: 3.22,
        shade: "C",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-PRL-WH-02",
        date: "2026-03-02",
        supplier: "Vardhman Textiles",
        buyer: "PRL (Polo Ralph Lauren)"
    },
    {
        rollNo: "008",
        quantity: 114,
        lab: [14.2, 0.8, 0.0],
        deltaE: 1.48,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-DR-BK-03",
        date: "2026-03-03",
        supplier: "Loyal Textile Mills",
        buyer: "Dressmann"
    },
    {
        rollNo: "009",
        quantity: 115,
        lab: [12.9, 1.6, 0.7],
        deltaE: 3.86,
        shade: "C",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-DR-BK-03",
        date: "2026-03-03",
        supplier: "Loyal Textile Mills",
        buyer: "Dressmann"
    },
    {
        rollNo: "010",
        quantity: 110,
        lab: [12.3, 2.0, 1.1],
        deltaE: 5.08,
        shade: "D",
        decision: "HOLD",
        image: null,
        orderId: "LOT-DR-BK-03",
        date: "2026-03-03",
        supplier: "Loyal Textile Mills",
        buyer: "Dressmann"
    },
    {
        rollNo: "011",
        quantity: 119,
        lab: [36.9, -6.8, 8.0],
        deltaE: 1.56,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-LA-GR-04",
        date: "2026-03-04",
        supplier: "Arvind Mills",
        buyer: "Lacoste"
    },
    {
        rollNo: "012",
        quantity: 117,
        lab: [34.6, -7.9, 6.1],
        deltaE: 4.26,
        shade: "D",
        decision: "HOLD",
        image: null,
        orderId: "LOT-LA-GR-04",
        date: "2026-03-04",
        supplier: "Arvind Mills",
        buyer: "Lacoste"
    },
    {
        rollNo: "013",
        quantity: 120,
        lab: [56.9, 1.1, 0.4],
        deltaE: 2.06,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-HM-GY-05",
        date: "2026-03-05",
        supplier: "Loyal Textile Mills",
        buyer: "H&M"
    },
    {
        rollNo: "014",
        quantity: 125,
        lab: [69.3, 5.7, 15.2],
        deltaE: 1.98,
        shade: "B",
        decision: "ACCEPT",
        image: null,
        orderId: "LOT-PRL-BG-06",
        date: "2026-03-06",
        supplier: "Arvind Mills",
        buyer: "PRL (Polo Ralph Lauren)"
    },
    {
        rollNo: "015",
        quantity: 123,
        lab: [67.9, 6.3, 13.8],
        deltaE: 4.18,
        shade: "D",
        decision: "HOLD",
        image: null,
        orderId: "LOT-PRL-BG-06",
        date: "2026-03-06",
        supplier: "Arvind Mills",
        buyer: "PRL (Polo Ralph Lauren)"
    },
    {
        rollNo: "016",
        quantity: 104,
        lab: [25.4, 2.4, 1.1],
        deltaE: 6.04,
        shade: "E",
        decision: "REJECT",
        image: null,
        orderId: "LOT-DR-CH-07",
        date: "2026-03-07",
        supplier: "Vardhman Textiles",
        buyer: "Dressmann"
    }
];
